### ISSUE TITLE
faciliate saving and exiting file instructions

### ISSUE THREAD

**Issue by nyxnor** [radio24/TorBox#125]
on branch v.0.5.0
text/advanced-OS-text
text/edit_clients_authorisation-text

```
CTRL-O followed with an ENTER to save the changes.
CTRL-X to exit the editor.
```

I CTRL-O asks if want to change the file name and have to use an extra command (ENTER).

`Ctrl+S+X` saves the file and exits the editor. What about it?

**Comment by radio24** [comment]
Thanks. I will change it with the next commit.

**Comment by radio24** [comment]
It is done in the latest commit: 0b3961a4f5912d19951645589bb44386d9c90523
