### ISSUE TITLE
make the version a variable

### ISSUE THREAD

**Issue by nyxnor** [radio24/TorBox#127]
I imagine you replace on every new release across the menus the version from previous to new.
If you put a `version.txt` and source it or a variable inside `torbox.lib`, then it will avoid outdated menu version when testing new releases as on https://github.com/radio24/TorBox/discussions/119

**Comment by radio24** [comment]
That's a good point. However, at the moment, it is labelled as `v.0.4.2` because, so far, we do not have an official release.
