### ISSUE TITLE
[QUESTION] mv and cp tor binaries, why?

### ISSUE THREAD

**Issue by nyxnor** [radio24/TorBox#129]
https://github.com/radio24/TorBox/blob/ff548f04ecc181f0a5ec5f43c2c6cdfc95256348/install/run_install.sh#L705
https://github.com/radio24/TorBox/blob/ff548f04ecc181f0a5ec5f43c2c6cdfc95256348/install/run_install.sh#L708

What is the reason this is needed?

**Comment by radio24** [comment]
I expired in the past that depending on how and on which operating system tor and geoip was installed, the binaries could be in different places, but I want them all in /usr/bin
