### ISSUE TITLE
ICMP/PING is not passing through TOR

### ISSUE THREAD

**Issue by johdn1010** [radio24/TorBox#15]
I have no 100% accurate way of verifing this, but when I ping something (from MY computer, not "TORBox OS"), the ping is very low and the same as if I ping it from my home connection. I've also figured out, that the pings are "GEO" Based on the location I'm from.. That makes me think, ping/icmp isn't "torrified" - over tor. 

I don't know if this is on purpose or no perhaps is there way of making it through tor? 
Please take a look, thank you so much!! 

I use the latest version torbox-20200112-v030.gz

**Comment by radio24** [comment]
Tor does not support ICMP, which is needed by ping. Tor does only support TCP. This has nothing to do with TorBox and is not a bug.

Possible solution:
Installing and using [httping](https://www.vanheusden.com/httping/)

**Comment by johdn1010** [comment]
Hi yes, I guess I've figured out back then. My bad.

But shouldn't it be better to add some IPtables rules, to simply just nullroute the ping? to everytime you try to ping something, forward the traffic to 127.0.0.1 along with other stuff that isn't going through tor? Just a suggestion.

thanks
