### ISSUE TITLE
No prevention Tor over Tor failures

### ISSUE THREAD

**Issue by Nonie689** [radio24/TorBox#158]
When I trying to setup orbot on my mobile device  I am not able to use the TorBox Hotspot.

But cause of my fucking xiaomi device I have often orbot killed without a fix in it. ( https://github.com/guardianproject/orbot/issues/701 )

  So the my real problem are, no real protection from connection without tor. (by app or by router)

why I am to need currently orbot, cause VOIP see:

https://github.com/radio24/TorBox/issues/151

**Comment by radio24** [comment]
Probably starting more than a year ago, it seems that the Tor network (or probably more correct Tor Relays) are refusing "[Tor over Tor](https://www.torbox.ch/?page_id=112#when-im-connected-with-torbox-and-use-the-tor-browser-or-tails-on-one-of-the-clients-isnt-that-a-risk-for-my-securityanonymity-tor-over-tor-scenario)" connections. Without using bridges and the option "This computer goes through a firewall that only allows connections to certain ports" (see [here](https://www.torbox.ch/?page_id=112#i-dont-care-about-the-tor-over-tor-scenario-and-just-want-to-use-the-tor-browser-but-it-cannot-connect-the-tor-network-through-torbox-what-can-i-do)) the Tor Browser cannot connect the Tor network over the TorBox showing following messages in the log-file:

```
[NOTICE] Bootstrapped 5% (conn): Connecting to a relay
[NOTICE] Bootstrapped 10% (conn_done): Connected to a relay
[WARN] Problem bootstrapping. Stuck at 10% (conn_done): Connected to a relay. (TLS_ERROR; TLS_ERROR; count 10; recommendation warn; host DD0219BD5B3015287C94BE1372534A7FDCAD9F32 at 82.165.111.170:443)
[WARN] 10 connections have failed:
[WARN] 10 connections died in state handshaking (TLS) with SSL state SSLv3/TLS write client hello in HANDSHAKE
```

As mentioned above, there is a solution: activate OBFS4 and the firewall-option. However, I don't know if that also will work for Orbot. At least, Orbot supports OBFS4 bridges.

Other than mentioned in the title of this issue, even if your hardware is buggy, I don't see a bug in TorBox. I will rename the title to prevent any confusion.
