### ISSUE TITLE
After Reboot. Need to reconnect Cellular.

### ISSUE THREAD

**Issue by ipwebnl** [radio24/TorBox#185]
Every time i reboot Raspberry pi 4. i need to reconnect Cellular. ( Open in the main menu option 8. Click yes. And it works. )

Need this option.. But not asked starting with TorBox v.0.4.0?
Do you want to activate the auto-connect / reconnect service at RPi boot up?
Depending on your use case, “Yes” or “No”.
( https://www.torbox.ch/?page_id=1030 )

**Comment by radio24** [comment]
I will look into it.

**Comment by radio24** [comment]
I added the functionality to reconnect an internet through a cellular connection if previously used to the `rc.local`, which is executed during the startup of the TorBox. It will be released with TorBox v.0.5.2, which should be ready in about a week.

You can already use that feature if you do one of the following possibilities:
- Edit your `rc.local` with sudo `nano /etc/rc.local` and add the following line (see [here](https://github.com/radio24/TorBox/blob/8bce382c9499edf7ad5023861101c2690302534b/etc/rc.local#L78)):
`if grep "INTERNET_IFACE=ppp0" /home/torbox/torbox/run/torbox.run ; then pon ; fi`
In my case, I had to wait al,ost a minute after the boot up until the client updated its routes.
- Download the raw `rc.local` file from TorBox v.0.5.2 with `wget https://raw.githubusercontent.com/radio24/TorBox/torbox-v0.5.2/etc/rc.local` and move the new rc.local to the right place : `sudo mv rc.local /etc/`
- Update your TorBox to v.0.5.2 with entry 5 and 6 in the Update and Maintenance sub-menu. Afterwards, you have to change the `run/torbox.run` file with `nano run/torbox.run` and to change the following:
```
Remove:
# Vanguards Repository
VANGUARDS_USED=https://github.com/mikeperry-tor/vanguards
VANGUARDS_COMMIT_HASH=10942de
VANGUARD_LOG_FILE="/var/log/tor/vanguards.log
# WiFi drivers from Fars Robotics
FARS_ROBOTICS_DRIVERS=http://downloads.fars-robotics.net/wifi-drivers/
Add:
# obfs4proxy repositories
OBFS4PROXY_USED=https://salsa.debian.org/pkg-privacy-team/obfs4proxy.git
# Exclude slow tor relays (Important: DO NOT ACTIVATE IF YOUR ANONYMITY HAS THE HIGHEST PRIORITY!)
# 0 - Not excluded
# 1 - Excluded
EX_SLOW=0
# TCS starting commands
# Syntax: TCS-<service_name>=<tcs command>
# This will configure the TCS program (do not remove or change that line - this is an anchor)

```

**Comment by ipwebnl** [comment]
can't wait for version 0.52. really like the project. already done more than 50 installations on different raspberry pi 4b. This was my first try with celular. thank you very much for all your work.
