### ISSUE TITLE
Use torbox as IP4 gateway?

### ISSUE THREAD

**Issue by HolyOne** [radio24/TorBox#205]
In whonix I can use the IP of the host PC as a gateway so not only my web traffic is encrytped but the whole traffic.
Does torbox have this feature?

I mean it encrypts wifi traffic so there should be a tor gateway in the wifi, but I only use ethernet.

Can you add an option for IP4 Gateway on ethernet on the terminal menu?

**Comment by radio24** [comment]
TorBox not only sends the web traffic through the tor network, but it also sends the entire incoming traffic through it. The only exception is connections directed to the TorBox itself, like SSH. It works not only with wifi traffic but also with ethernet. For more information, see [here](https://www.torbox.ch/?page_id=775).

If you connect your client to the TorBox with an ethernet cable, TorBox will automatically detect that by using entries 5-10 on the main menu. There is no need to add another entry to tell TorBox that there is an ethernet client. See [here](https://www.torbox.ch/?page_id=112#my-torbox-is-connected-with-the-internet-via-ethernet-im-using-onboard-wifi-for-my-client-devices-how-can-i-additionally-connect-a-cable-client) for an example of such a type of connection.
