### ISSUE TITLE
Forgotten connection

### ISSUE THREAD

**Issue by julosz** [radio24/TorBox#221]
I have installed the 0.5.2 version. After initialisation (connection is achieved through the eth0 interface) it has worked without issues. After restarting the Raspberry Pi it couldn’t connect to the internet (I have tried it many times). I have run the initialisation script once more, after that it could connect to the internet untill the next restart.
I have tried with various routers and various Raspberries (3,4) the issue persisted.

Any idea why it could be? 

Snippet from the log:

```
May 08 10:29:04.698 [notice] Read configuration file "/usr/share/tor/tor-service-defaults-torrc".
May 08 10:29:04.698 [notice] Read configuration file "/etc/tor/torrc".
May 08 10:29:04.702 [notice] Opening Socks listener on 127.0.0.1:9050
May 08 10:29:04.702 [notice] Opened Socks listener connection (ready) on 127.0.0.1:9050
May 08 10:29:04.702 [notice] Opening Socks listener on 192.168.42.1:9050
May 08 10:29:04.702 [notice] Opened Socks listener connection (ready) on 192.168.42.1:9050
May 08 10:29:04.702 [notice] Opening Socks listener on 127.0.0.1:9052
May 08 10:29:04.702 [notice] Opened Socks listener connection (ready) on 127.0.0.1:9052
May 08 10:29:04.702 [notice] Opening Socks listener on 192.168.42.1:9052
May 08 10:29:04.702 [notice] Opened Socks listener connection (ready) on 192.168.42.1:9052
May 08 10:29:04.702 [notice] Opening DNS listener on 127.0.0.1:9053
May 08 10:29:04.702 [notice] Opened DNS listener connection (ready) on 127.0.0.1:9053
May 08 10:29:04.702 [notice] Opening DNS listener on 192.168.42.1:9053
May 08 10:29:04.702 [notice] Opened DNS listener connection (ready) on 192.168.42.1:9053
May 08 10:29:04.702 [notice] Opening Transparent pf/netfilter listener on 127.0.0.1:9040
May 08 10:29:04.703 [notice] Opened Transparent pf/netfilter listener connection (ready) on 127.0.0.1:9040
May 08 10:29:04.703 [notice] Opening Transparent pf/netfilter listener on 192.168.42.1:9040
May 08 10:29:04.703 [notice] Opened Transparent pf/netfilter listener connection (ready) on 192.168.42.1:9040
May 08 10:29:04.703 [notice] Opening Control listener on 127.0.0.1:9051
May 08 10:29:04.703 [notice] Opened Control listener connection (ready) on 127.0.0.1:9051
May 08 10:29:04.000 [notice] Not disabling debugger attaching for unprivileged users.
May 08 10:29:04.000 [notice] Parsing GEOIP IPv4 file /usr/local/share/tor/geoip.
May 08 10:29:04.000 [notice] Parsing GEOIP IPv6 file /usr/local/share/tor/geoip6.
May 08 10:29:05.000 [notice] Bootstrapped 0% (starting): Starting
May 08 10:29:06.000 [notice] Starting with guard context "default"
May 08 10:29:06.000 [notice] Signaled readiness to systemd
May 08 10:29:07.000 [notice] Failed to find node for hop #1 of our path. Discarding this circuit.
May 08 10:29:07.000 [notice] Our circuit 0 (id: 31) died due to an invalid selected path, purpose General-purpose client. This may be a torrc configuration issue, or a bug.
May 08 10:29:08.000 [notice] Opening Control listener on /run/tor/control
May 08 10:29:08.000 [notice] Opened Control listener connection (ready) on /run/tor/control
May 08 10:29:43.000 [notice] Failed to find node for hop #1 of our path. Discarding this circuit.


```
```

**Comment by radio24** [comment]
Please, check if the clock of the Raspberry Pi is synchronized with UTC --> https://time.is/UTC

**Comment by julosz** [comment]
Thank you for your reply. :)

In the meantime I have discovered that if I use eth0, the automatic time synchronization doesn't work, but after setting it up manually, tor works just fine with the eth0.

But if instead of the eth0 I use two wifi adapters at once (one internal and one external dongle), then the tor network is accessible, the automatic time synchronization also runs fine, even after several restarts. So using two wireless interfaces, it works like a charm.

I'll also look into the things you have suggested and I'll try them gradually. I'll keep you informed.

**Comment by radio24** [comment]
Try to update the `[rc.local](https://github.com/radio24/TorBox/commits/master/etc/rc.local)` with the following procedure:
- Update the TorBox menu with entry 5 in the [Update and Maintenance sub-menu](https://www.torbox.ch/?page_id=1410).
- Press ESC until you are on the Command Line Interface.
- Use the following commands:
-- `cd`
-- `sudo cp /etc/rc.local /etc/rc.local.bak`
-- `sudo cp torbox/etc/rc.local /etc/rc.local`
-- `chmod a+x /etc/rc.local`
- Restart TorBox

If this doesn't help, tray to use sudo `dhclient eth0` immediately after booting TorBox. I am grateful for any feedback.

**Comment by julosz** [comment]
Thank you for your reply. 

I’ve tried both solutions. First the snippet  with `chmod` [1], after that the `sudo dhclient eth0` snippet as well (and the tor networks works via eth0 !!!). If i run the command `sudo dhclient eth0` after a every reboot, tor works! 

Can this command somehow be added to a config file so I wont have to run it manually?

Edit: `sudo` command is needed when executing `chmod` in [1]

**Comment by radio24** [comment]
Try the following:
- Open `/etc/rc.local` with `sudo nano /etc/rc.local`
- Add above `sleep 5` (see [here](https://github.com/radio24/TorBox/blob/80020110b4863b8cf253f8c0bc6498e6fa843d98/etc/rc.local#L114)) the following command: `dhclient -r`. 

That should work with all interfaces. If this causes problems, you could also use `dhclient eth0` instead of `dhclient -r`. However, because that will only work with `eth0`, I'm not sure if there are any side effects if `eth0` is not connected.

I'm looking for your feedback. I may add that as default into torbox-0.5.3.

**Comment by julosz** [comment]
Hello. 

I have created an entirely new installation. Adding `dhclient -r` to rc.local didn’t help, but adding `dhclient eth` did. 
So the definitive solution is to insert `dhclient eth` to rc.local (before line `sudo systemctl start dnsmasq` since my file doesn’t contain the `sleep 5` command mentioned above in your answer). 

Thanks a lot for your help.

**Comment by radio24** [comment]
Thanks for the feedback.
I didn't hear that someone else had a similar problem. However, I will let the thread open, so that other people with same or similar problems can add a comment.

**Comment by radio24** [comment]
The issue may be fixed with TorBox v.0.5.3 - waiting on feedback

**Comment by julosz** [comment]
Thank you. I confirm, using TorBox v.0.5.3 solves the problem. The solution explained in my previous comment is valid as well.
