### ISSUE TITLE
Problems adding tor Exit nodes

### ISSUE THREAD

**Issue by Strommberg** [radio24/TorBox#23]
Hello i have problems adding Tor Exit nodes. If i add them i have no Internet connection.

Torrc:
# This is the configuration file of Tor

######################################################
## Configuration for TorBox
StrictExitNodes 1
ExitNodes $97F51AF6791AD33981CE25DC7A2618429F25B3B0, $68EC657DC8A587B38D5D7763D5C72E93C2CD456C,
$A2DD0EF31813E9B7F6DB435504A406E1AD2B76AB, $FDCFEA18CC64461455DE5EA3FC31834C6B42FEC7,
$9AD90317DDA2F898EB0AE0F20976EA97E7AF9012, $6B61EFE3AEDEB3351FD3C910443D95556316E01C,
$22296CB6AE56609A96F02FB843AB7B4B0A31CAF4, $844DC3890E4D04473D10EE65547491F200A86F89
Log notice file /var/log/tor/notices.log
VirtualAddrNetworkIPv4 10.192.0.0/10
AutomapHostsSuffixes .onion,.exit
AutomapHostsOnResolve 1
TransPort 192.168.42.1:9040
#TransPort 192.168.43.1:9040
DNSPort 192.168.42.1:9053
#DNSPort 192.168.43.1:9053
SocksPort 192.168.42.1:9050
#SocksPort 192.168.43.1:9050
DisableDebuggerAttachment 0
ControlPort 9051
HashedControlPassword 16:E68F16640ED8C0F7601F5AA3D229D8DFD8715623CB055577F9434F7FB7
######################################################
## This will setup an obfs4 bridge relay.
#BridgeRelay 1
#ORPort 4235
#ExtORPort auto
#ServerTransportPlugin obfs4 exec /usr/bin/obfs4proxy
#ServerTransportListenAddr obfs4 0.0.0.0:443
#ContactInfo <address@email.com>
#Nickname TorBox031

######################################################
## otherwise.
#ReachableAddresses *:80, *:443

######################################################
## If you like to use bridges to overcome censorship, EDIT THE LINES BELOW!
.......

**Comment by radio24** [comment]
Hello Strommberg

TorBox doesn't support or recommend to use the "ExitNodes" directive. As the [Tor manual](https://2019.www.torproject.org/docs/tor-manual.html.en) states, if not used right, "you can degrade functionality." In my opinion, this directive also worse the possibility of remaining anonymous.

Nevertheless, the directive should work without any problem with TorBox. To test it, I flashed the latest TorBox image ([torbox-20200530-v031.gz](https://www.torbox.ch/data/torbox-20200530-v031.gz)) and added the following line into torrc (right before the Log-directive:
`ExitNodes $97F51AF6791AD33981CE25DC7A2618429F25B3B0,$68EC657DC8A587B38D5D7763D5C72E93C2CD456C,$A2DD0EF31813E9B7F6DB435504A406E1AD2B76AB,$FDCFEA18CC64461455DE5EA3FC31834C6B42FEC7,$9AD90317DDA2F898EB0AE0F20976EA97E7AF9012, $6B61EFE3AEDEB3351FD3C910443D95556316E01C,$22296CB6AE56609A96F02FB843AB7B4B0A31CAF4,$844DC3890E4D04473D10EE65547491F200A86F89`

Then I restarted Tor, and it worked without any problem. Note that all fingerprints are in one single line. The space between the coma and the $-sign is unnecessary but doesn't break anything.

Next, I added "StrictExitNodes 1" to the torrc and restarted Tor again. All worked as intended. I tested it with Tor version 0.4.2.7.

I would recommend you to try the following:
- Restore the original torrc: 
  cd ~
  sudo cp torbox/etc/tor/torrc /etc/tor
- Start the TorBox menu, go to the update and reset sub-menu (main menu entry 12) and choose option 8 to reset Tor
- Then go to the countermeasure submenu and chose menu entry 8 to add the StrictExitNodes and the ExitNodes directives.
- Then chose in the same submenu entry 9 to restart Tor and to check the output. Restarting Tor can take some time. If you still have problems, please post the printed output.
