### ISSUE TITLE
Missing IP Address

### ISSUE THREAD

**Issue by gozillah** [radio24/TorBox#277]
When starting the wireless manager from the main menu after boot, the wireless menu will as per default automatically connect to the most recent WiFi AP (if available), showing its IP address in square brackets. However the wireless menu will sometimes only show a "-" in square brackets.

![Issue](https://github.com/radio24/TorBox/assets/156078441/bc72a8c5-0c54-4bcf-a3e1-c8a538caddef)

**Comment by radio24** [comment]
Yes, that's the situation when the WiFi is connected, but the interface doesn't get an IP address. There are different reasons for this. I don't know if Zotil can mitigate this situation. He may have time to look at it and let us know.

**Comment by zotil** [comment]
> However the wireless menu will sometimes only show a "-" in square brackets.

Thanks for flagging this. The "-" signifies that the IP address is being retrieved in the background. Perhaps we could consider changing it to "Obtaining IP" for clarity.
