### ISSUE TITLE
how to uninstall torbox

### ISSUE THREAD

**Issue by herotux** [radio24/TorBox#29]
Maybe we have an script to uninstall torbox from raspberry pi os??

**Comment by radio24** [comment]
Hello Herotux
No. TorBox is coming as an image file or is supposed to be installed on a clean Raspbery Pi OS. TorBox is not supposed to be installed on a working machine. For that reason, if you want to remove TorBox, just write an new image file on the SD card.
We may consider in the long term to offer a removal tool, however, currently we have other priorities.
