### ISSUE TITLE
Can use Raspberry Pi 3 Model B? Mine is notRaspberry Pi 3 Model B +

### ISSUE THREAD

**Issue by yyuyul** [radio24/TorBox#301]
TROBOX is absolutely  good. Can I use Raspberry Pi 3 Model B instead of Raspberry Pi 3 Model B +? Has anyone tried it with Raspberry Pi 3 Model B ? Now I haven't decided yet whether to use torbox.

**Comment by radio24** [comment]
Check this: [Why isn’t TorBox compatible with the Raspberry Pi 3 Model B or older hardware… and why don’t you offer a 32-bit version of TorBox?](https://www.torbox.ch/?page_id=112#why-isnt-torbox-compatible-with-the-raspberry-pi-3-model-b-or-older-hardware-and-why-dont-you-offer-a-32-bit-version-of-torbox)
