### ISSUE TITLE
Torbox does not load main menu

### ISSUE THREAD

**Issue by LuckySkullThe420th** [radio24/TorBox#321]
Hello,

I installed Torbox through the installation script & followed the instructions to ssh into the pi. The instructions said that there would be a main menu that would open when I ssh into my machine, but that was not the case I was met with a command line & no instruction on how to move forward. Can someone please help me?

**Comment by radio24** [comment]
Yes. After the login with SSH do the following:
```
cd
cd torbox
./menu
```
