### ISSUE TITLE
Tor bootstrap takes an abnormal amount of time, plus some configuration issues with services

### ISSUE THREAD

**Issue by LuckySkullThe420th** [radio24/TorBox#322]
I've been messing around with my manual build of torbox all day & night trying to connect to the internet, but I've had no luck. I've had a few problems with my tor@default.service & isc-dhcp-server.service because both of them would not start upon reboot. I learned that my IPs were not set & they never set upon boot. They disappear after a reboot, then I'm subject to the horrors of these failing services again. After successfully starting up both, I was finally able to restart & begin the bootstrap for tor, but even as we speak the connection is stuck at 0%... I've checked the logs & everything seems fine. But I don't know what else to do.

**Comment by radio24** [comment]
We are investigating it. 
Raspberry Pi OS apparently removed the `ifupdown` package from its latest images, which caused these problems. We are currently trying out the latest changes and will post more information here if our tests are successful.

**Comment by LuckySkullThe420th** [comment]
Ok, thank you.
