### ISSUE TITLE
Torbox Mini compressed image corrupt?

### ISSUE THREAD

**Issue by airgap0** [radio24/TorBox#332]
When one tries to flash torbox mini to a SD RasperryPi-Imager v 1.8.5, Balena Etcher portable 1.18.4 and 7Zip 23.01 (x64) report a compression error. So it seems torbox-mini-20241208-v054.img.xz has an issue although the hash is identical to the published hash. See attached screendump. 
<img width="671" alt="torboxminicompress" src="https://github.com/user-attachments/assets/00805946-eea9-41ed-8cca-e08837407824" />
Therefore one can safely assume the download itself was free from transmission errors.

**Comment by radio24** [comment]
Thank you for the feedback.
I don't know what, but something went wrong with the compression.
The file will be replaced as soon as I have built a new xz-file, tested and uploaded it.
I will make sure to keep you posted in this thread.

**Comment by radio24** [comment]
The new image file is now online: [TorBox mini v.0.5.4 (08.12.2024)](https://www.torbox.ch/data/torbox-mini-20241208-v054.img.xz), the [SHA-256 values](https://www.torbox.ch/?page_id=1128) is updated.

**As information**: Balena Etcher and the Raspberry Pi Imager refuse to write the `.xz` file. However, unpacking with 7Zip should work now without a problem. See attached screen dump.
<img width="519" alt="7z test 2024-12-19 20 05 58" src="https://github.com/user-attachments/assets/dc71ffc5-a963-4c38-839f-fc520f906feb" />

**Comment by airgap0** [comment]
New xz does the job - Thank You
