### ISSUE TITLE
how to share tor network via eth1

### ISSUE THREAD

**Issue by connected201** [radio24/TorBox#42]
hi, i have 2 eth. (1 onboard, 1 USB) i want to connect raspberry via eth0 to receive internet, and share via eth1 (USB network card) how i can configure to obtain this setup? best regards

**Comment by radio24** [comment]
Are you speaking about TorBox or about the Raspberry Pi in general?

**Comment by connected201** [comment]
about TorBox, i have second ethernet adapter
![image](https://user-images.githubusercontent.com/20506433/120292910-6562f380-c2cd-11eb-86b6-22cb8044f105.png)
for first eth0 i want to receive internet, and for second eth1 i want to share internet over TOR network

**Comment by radio24** [comment]
This is easy. 
Shutdown TorBox - connect the Internet router to eth0 - connect your USB ethernet adapter (eth1) and connect your client with it - start TorBox - chose entry 4 in the TorBox main menu. That's it!

**IMPORTANT**
To access the TorBox from a such client, you have to use 192.168.**43**.1. The client will get a 192.168.43.x address.

For more information see here: 
- [Documentation - Main Menu ](https://www.torbox.ch/?page_id=775)
- [FAQ - My TorBox is connected with the Internet via ethernet.  I’m using onboard WiFi for my client devices. How can I additionally connect a cable client?](https://www.torbox.ch/?page_id=112#my-torbox-is-connected-with-the-internet-via-ethernet-im-using-onboard-wifi-for-my-client-devices-how-can-i-additionally-connect-a-cable-client)
