### ISSUE TITLE
Can't  disable torbox wlan

### ISSUE THREAD

**Issue by xRzvD8wjjRth** [radio24/TorBox#47]
I want to use torbox only through ethernet cable
I try to disable torbox wlan through the appropriate menu but it doesn't work,
it is always among the available wi-fi networks

**Comment by radio24** [comment]
We cannot reproduce your difficulties. We tested the functionality in the following way:

- Connect the client [as described in the FAQ](https://www.torbox.ch/?page_id=112#my-torbox-is-connected-with-the-internet-via-ethernet-im-using-onboard-wifi-for-my-client-devices-how-can-i-additionally-connect-a-cable-client), enabled Ethernet and disabled WiFi on the client -> the client automatically gets its IP address (192.268.43.10), but cannot reach the Internet, yet.
- Start an SSH client application on the client, log into the TorBox (192.268.43.1), and chose entry 4 in the [main menu](https://www.torbox.ch/?page_id=775) to route Internet through tor to the client -> client can reach the Internet through tor.
- Chose entry 9 in the [configuration sub-menu](https://www.torbox.ch/?page_id=875) to disable TorBox's WLAN temporary. Switch WiFi off and on on the checking device to be sure that it clears the SSID cache  -> result: checking device doesn't show the TorBox WLAN anymore.
- Reboot TorBox  -> TorBox's WLAN is again up and running.
- Chose entry 9 in the configuration sub-menu to disable TorBox's WLAN permanently. Switch WiFi off and on on the checking device to be sure that it clears the SSID cache  -> result: checking device doesn't show the TorBox WLAN anymore.
- Reboot TorBox  -> TorBox's WLAN is still down.
- Chose entry 9 in the configuration sub-menu to permanently enable TorBox's WLAN again -> result: checking device shows the TorBox WLAN again.

Conclusion: the functionality to temporary or permanently disable TorBox's WLAN does work as intended.
