### ISSUE TITLE
SD Card Expansion?

### ISSUE THREAD

**Issue by MAkcanca** [radio24/TorBox#61]
Hi, I've been reading through the source code but couldn't encounter anything related to sd card partition expansion. How does TorBox handle this, or does it ever?

Thanks!

**Comment by radio24** [comment]
The TorBox image is compressed with [PiShrink](https://raw.githubusercontent.com/Drewsif/PiShrink/master/pishrink.sh).

After flashing the image on a SD Card and starting up the SD Card for the first time, the partition is expanded over the whole available space on the SD Card. However, this is not part of TorBox.

**Comment by MAkcanca** [comment]
Great, thanks!
Since shrink/expand part is not a part of source code we can close this issue now.
