### ISSUE TITLE
project reuse

### ISSUE THREAD

**Issue by nyxnor** [radio24/TorBox#65]
[GPL v3.0 summary](https://github.com/radio24/TorBox/blob/master/LICENSE) **Permissions of this strong copyleft license are conditioned on making available complete source code of licensed works and modifications, which include larger works using a licensed work, under the same license. Copyright and license notices must be preserved. Contributors provide an express grant of patent rights.**

I'm using the bridges for the client scripts: meek-azure, snowflake, the 4 bridges_*.
I preserved the verbatim inside the files.
I need to add the license file somewhere in the code or the verbatim inside the files are enough?

**Comment by radio24** [comment]
You can use the scripts for your purpose. It has to be published under GPL v3.0, or (at your option) any later version. The verbatim inside the files is enough. Of course, if you modify the script, you can also change the verbatim inside the file (for example add yourself as a contributor) as long as it not in opposition to the GPL v3.0.
