### ISSUE TITLE
LTE Stick not working on TorBox!

### ISSUE THREAD

**Issue by iisaac404** [radio24/TorBox#66]
I have installed Torbox on Raspberry pi 4 and I have tried it with the ethernet cable, everything is good.
but when I want to run it with the modem (Huawei E3372), I receive "there is no cellular link or an USB dongle connected!"

- the modem works on the pc without a driver
thanks

**Comment by radio24** [comment]
Could you please run the following command on TorBox's terminal (after leaving the main menu with ESC) and post the result:
`ifconfig -a`
