### ISSUE TITLE
SC2154: sOBSF4PORT is referenced but not assigned

### ISSUE THREAD

**Issue by nyxnor** [radio24/TorBox#92]
https://github.com/radio24/TorBox/blob/fb4d490a89b659386a98e7d77c0c7104428fa48f/menu-server#L204

https://www.shellcheck.net/wiki/SC2154

I don't know what this variable is supposed to be to correct it

**Comment by radio24** [comment]
Don't change it. Some variables are used by the torbox.lib, which is not included by shellcheck.

**Comment by nyxnor** [comment]
Ok, I understand know why. The option `-x` for shellcheck also checks the source, but it can not check in this case because it is inside a function `deactivating_bridge_relay`.
