### ISSUE TITLE
Script=update. Error=SC2153: Possible misspelling: CHECK_HD4 may not be assigned, but CHECK_HD3 is.

### ISSUE THREAD

**Issue by nyxnor** [radio24/TorBox#93]
https://github.com/radio24/TorBox/blob/fb4d490a89b659386a98e7d77c0c7104428fa48f/update#L598

https://www.shellcheck.net/wiki/SC2153

**Comment by radio24** [comment]
CHECK_HD4 can be removed - it is obsolete in this script.

**Comment by nyxnor** [comment]
https://github.com/radio24/TorBox/pull/91/commits/f9fb10999ab24cb72e41345148ad1a2ad0f0c4b5
