### ISSUE TITLE
change sed delimiter when dealing with urls

### ISSUE THREAD

**Issue by nyxnor** [radio24/TorBox#98]
Aiming to remove`REPLACEMENT_STR` for example: https://github.com/radio24/TorBox/blob/8e24af1521ed555f6d8ff9959c0b940b0423078c/install/run_install.sh#L1078
use `|` as delimiter.
```sh
$ echo $GO_DL_PATH 
https://golang.org/dl/
$ cat example.txt 
GO_DL_PATH=
$ sed "s|GO_DL_PATH=.*|GO_DL_PATH=${GO_DL_PATH}|" example.txt 
GO_DL_PATH=https://golang.org/dl/
```

This does not work with `[]` which happens to be on ipv6 bridges. So this can't be changed yet until a compatible delimiter is found:
https://github.com/radio24/TorBox/blob/8e24af1521ed555f6d8ff9959c0b940b0423078c/bridges_deactivate_old#L137

I mean, yeah, replacement string substitutes every character that could break regex, but it is not necessary when dealing with links.

**Comment by radio24** [comment]
This is a good point, and I will add this to CONTRIBUTING.md. When changing/adapting the code, that can be taken into account. However, I won't spend my time changing this in about 90 places in the code.
